In [2]:
import torch
import numpy as np

# 打印cuda设备, 显卡名字
print(torch.cuda.get_device_name(0))


NVIDIA GeForce GTX 1650


 ### 1 pytorch张量
 

In [5]:
# pytorch中的张量和tensorflow的tensor是一样, 名字都一样
# pytorch中的张量也叫tensor
# tensor和numpy中的ndarray也是一个意思, 只不过tensor可以在GPU上加速计算

In [8]:
# 创建tensor
torch.tensor([6, 2], dtype=torch.int32)

tensor([6, 2], dtype=torch.int32)

In [6]:
torch.tensor((6, 2))

tensor([6, 2])

In [9]:
torch.tensor(np.array([6, 2]))

tensor([6, 2])

In [12]:
# 快速创建tensor的方法, 和numpy中的routines方法一样
# ones, zeros, full, eye, random.randn, random.normal...arange...  random.rand, random.random
# 创建一个0到1之间的随机数组成的tensor
# torch.rand((2, 3))
torch.rand(2, 3)

tensor([[0.5048, 0.8711, 0.2493],
        [0.2362, 0.0659, 0.0883]])

In [13]:
# 标准正态分布

tensor([[-1.4264, -1.1923,  0.3757],
        [ 0.1623, -0.6290, -1.3995]])

In [14]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
# tensor的shape
x = torch.ones(2, 3, 4)
x.shape


torch.Size([2, 3, 4])

In [18]:
# 通过x.size()方法获取形状
x.size()

torch.Size([2, 3, 4])

In [20]:
# size中可以传shape的索引
x.size(0)

2

### 2 tensor中的基础数据类型

- 32位浮点数: torch.float32
- 64位浮点数: torch.float64
- 32位正数: torch.int32
- 16位正数: torch.int16
- 64位正数: torch.int64

In [22]:
# 我们可以在创建tensor时候指定数据类型
torch.tensor([6, 2], dtype=torch.float32)

tensor([6., 2.])

In [8]:
import tensorflow as tf

In [ ]:
# tensorflow 不能直接用tensor方法来创建tensor
# tensorflow提供了constant, Variable
# keras: deeplearning for human


In [4]:
# tensor和ndarray很方便的进行转化
n = np.random.randn(2, 3)
n 

array([[ 0.14025307, -0.7967703 ,  0.40756823],
       [ 0.29798267,  1.17992965, -0.38567549]])

In [5]:
a = torch.from_numpy(n)

In [6]:
a.numpy()

array([[ 0.14025307, -0.7967703 ,  0.40756823],
       [ 0.29798267,  1.17992965, -0.38567549]])

In [9]:
t = tf.constant(a)
t

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 0.14025307, -0.7967703 ,  0.40756823],
       [ 0.29798267,  1.17992965, -0.38567549]])>

In [10]:
t.numpy()

array([[ 0.14025307, -0.7967703 ,  0.40756823],
       [ 0.29798267,  1.17992965, -0.38567549]])

### 3 张量运算

In [11]:
# tensor运算规则和numpy的ndarray很像
# 和单个数字运算
t = torch.ones(2, 3)
t


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
t + 3

tensor([[4., 4., 4.],
        [4., 4., 4.]])

In [13]:
torch.add(t, 3)

tensor([[4., 4., 4.],
        [4., 4., 4.]])

In [14]:
x1 = torch.ones(2, 3)

In [15]:
# 对应位置的元素相加, element-wise操作 残差网络的加法就是
x1 + t


tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [16]:
# 有输出不会改变原始值
t.add(x1)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [17]:
t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [18]:
# 如果想改变原始值, pytorch中带下划线的操作会改变原始值
t.add_(x1)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [19]:
t

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [ ]:
torch.inverse()

In [20]:
# 改变tensor的形状
t.reshape(3, 2)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [21]:
t.view(3, 2)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [22]:
# 聚合操作
t.mean()

tensor(2.)

In [23]:
t.sum()

tensor(12.)

In [25]:
# 指定维度进行聚合, 不写维度, 默认会把所有维度聚合掉
x = t.sum(dim=1)

In [26]:
x

tensor([6., 6.])

In [33]:
x = x.sum()

In [34]:
# 一个数字叫做scalars(标量), 带中括号的数据叫做向量
# item是专门用来取出tensor中的标量的值
x.item()

12.0

In [35]:
x = torch.randn(3, 4)
x

tensor([[ 2.0250, -0.4548, -2.6171,  0.1076],
        [ 0.9041,  1.2178,  0.5809, -0.0281],
        [ 2.4892, -1.0142,  0.4497,  0.5614]])

In [36]:
x[0]

tensor([ 2.0250, -0.4548, -2.6171,  0.1076])

In [37]:
x[0][0]

tensor(2.0250)

In [39]:
# tensor的切片和索引操作和ndarray是完全一样
x[0][:3]

tensor([ 2.0250, -0.4548, -2.6171])

In [40]:
x = torch.randn(32, 224, 224, 3)

In [41]:
# 取出图片数据
x[0, :, :,0].shape

torch.Size([224, 224])

In [42]:
# 矩阵乘法
a1 = torch.randn(2, 3)
a2 = torch.randn(3, 5)
torch.matmul(a1, a2)


tensor([[-0.2136, -1.3336, -0.4717,  0.2775, -0.2150],
        [ 1.8284,  0.3088, -2.8366,  1.5644, -1.1105]])

In [43]:
# @ 也是矩阵点乘快捷写法
a1 @ a2

tensor([[-0.2136, -1.3336, -0.4717,  0.2775, -0.2150],
        [ 1.8284,  0.3088, -2.8366,  1.5644, -1.1105]])

In [44]:
# pytorch中的dot是向量的乘法, 必须是一维向量
a1.dot(a2)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [46]:
x1 = torch.rand(5)
x2 = torch.rand(5)
print(x1, x2)
x1.dot(x2)

tensor([0.4130, 0.5820, 0.5368, 0.0909, 0.4517]) tensor([0.8546, 0.2481, 0.2910, 0.9068, 0.7903])


tensor(1.0930)

In [47]:
(x1 * x2).sum()

tensor(1.0930)

### 4张量的自动微分

In [49]:
# 说白了就是自动求导
# 在要求导的变量定义中加上requires_grad=True表示要追踪这个变量的导数
x = torch.ones(2, 2, requires_grad=True)
y = x + 2


In [50]:
x.requires_grad

True

In [52]:
x2 = torch.ones(2, 2)

In [55]:
# 默认是不会自动求导
x2.requires_grad

False

In [56]:
y.grad_fn

In [59]:
# 导数必须由标量输出创建, 意思就是说你要求的最后的结果, 必须是一个标量, 不能是向量
y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [75]:
# z = y.mean()
xy = y.sum()

In [76]:
# 只有执行完backward之后, 所有requires_grad=True的变量的导数都会被自动求出
# z.backward()
xy.backward()

In [78]:
# x.grad
x.grad

tensor([[7., 7.],
        [7., 7.]])

In [63]:
z = y * y * 3
out = z.mean()

In [64]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [65]:
out.backward()

In [66]:
y.grad

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11924\486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:499.)
  y.grad


In [71]:
# 求非叶子节点的tensor的导数, 必须使用retain_grad, 不然会报警告
y.retain_grad

<function Tensor.retain_grad()>

In [70]:
y.grad

In [79]:
# 如果不需要求导, 可以把代码包在torch.no_grad()中
x.requires_grad

True

In [80]:
(x ** 2).requires_grad

True

In [81]:
# 通过with torch.no_grad() 暂时不对x求导
with torch.no_grad():
    print((x ** 2).requires_grad)

False


In [82]:
x.requires_grad

True

In [83]:
y = x ** 2 + 2
y.requires_grad

True

In [84]:
y.detach()

tensor([[3., 3.],
        [3., 3.]])

In [85]:
y.requires_grad

True

In [86]:
x.detach()

tensor([[1., 1.],
        [1., 1.]])

In [87]:
y = x ** 2 + 2

In [88]:
y.requires_grad

True

In [89]:
y = x.detach()

In [90]:
y.requires_grad

False

In [92]:
# 除了在定义变量的时候指定requires_grad, 也可以通过requires_grad_()方法修改变量的requires_grad属性
a = torch.randn(2, 2)
a = a * 3 + 2
print(a.requires_grad)

False


In [93]:
a.requires_grad_(True)

tensor([[ 1.4200,  4.7543],
        [-1.2161,  0.4994]], requires_grad=True)

In [94]:
print(a.requires_grad)

True
