In [3]:
import torch
import numpy as np

# 打印cuda设备, 显卡名字
print(torch.cuda.get_device_name(0))


NVIDIA GeForce GTX 1650


 ### 1 pytorch张量
 

In [5]:
# pytorch中的张量和tensorflow的tensor是一样, 名字都一样
# pytorch中的张量也叫tensor
# tensor和numpy中的ndarray也是一个意思, 只不过tensor可以在GPU上加速计算

In [8]:
# 创建tensor
torch.tensor([6, 2], dtype=torch.int32)

tensor([6, 2], dtype=torch.int32)

In [6]:
torch.tensor((6, 2))

tensor([6, 2])

In [9]:
torch.tensor(np.array([6, 2]))

tensor([6, 2])

In [12]:
# 快速创建tensor的方法, 和numpy中的routines方法一样
# ones, zeros, full, eye, random.randn, random.normal...arange...  random.rand, random.random
# 创建一个0到1之间的随机数组成的tensor
# torch.rand((2, 3))
torch.rand(2, 3)

tensor([[0.5048, 0.8711, 0.2493],
        [0.2362, 0.0659, 0.0883]])

In [13]:
# 标准正态分布

tensor([[-1.4264, -1.1923,  0.3757],
        [ 0.1623, -0.6290, -1.3995]])

In [14]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
# tensor的shape
x = torch.ones(2, 3, 4)
x.shape


torch.Size([2, 3, 4])

In [18]:
# 通过x.size()方法获取形状
x.size()

torch.Size([2, 3, 4])

In [20]:
# size中可以传shape的索引
x.size(0)

2

### 2 tensor中的基础数据类型

- 32位浮点数: torch.float32
- 64位浮点数: torch.float64
- 32位正数: torch.int32
- 16位正数: torch.int16
- 64位正数: torch.int64

In [22]:
# 我们可以在创建tensor时候指定数据类型
torch.tensor([6, 2], dtype=torch.float32)

tensor([6., 2.])

In [24]:
import tensorflow as tf

In [ ]:
# tensorflow 不能直接用tensor方法来创建tensor
# tensorflow提供了constant, Variable
# keras: deeplearning for human


In [26]:
# tensor和ndarray很方便的进行转化
n = np.random.randn(2, 3)
n 

array([[ 0.08794652,  1.66446879, -0.67112078],
       [-1.62675174, -1.08080863, -1.41376892]])